/**
 * Integrations & lead-source connections.
 *
 * Architecture: an org can connect a lead source (WhatsApp, Facebook,
 * IndiaMART, Shopify, webhook, API…) by generating a unique webhook secret +
 * URL, or by saving provider config (kept server-side only). This module never
 * pretends a connection works without credentials — every "connect" action is
 * explicit and reversible.
 *
 *  - GET    /           catalog + the org's current connections
 *  - POST   /:source/connect    create/refresh a webhook secret (manager+)
 *  - PATCH  /:source   update config / enabled / status
 *  - DELETE /:source   disconnect (manager+)
 */
import crypto from 'crypto';
import { Router } from 'express';
import { prisma } from '../lib/prisma';
import { asyncHandler, badRequest, ok, validate } from '../lib/http';
import { requireAuth, requirePermission, assertManagerOrAbove, type AuthedRequest } from '../middleware/auth';
import { integrationUpdateSchema } from '../validators/schemas';
import { audit } from '../lib/audit';
import { config } from '../config';

const router = Router();
router.use(requireAuth);

export const INTEGRATION_CATALOG = [
  { source: 'WHATSAPP', name: 'WhatsApp Business', description: 'Send enquiries straight into your CRM from WhatsApp conversations.', kind: 'webhook', icon: 'MessageCircle' },
  { source: 'FACEBOOK', name: 'Facebook Lead Ads', description: 'Capture leads from your Facebook page lead forms automatically.', kind: 'webhook', icon: 'Facebook' },
  { source: 'INSTAGRAM', name: 'Instagram', description: 'Turn Instagram DMs and profile visits into tracked leads.', kind: 'webhook', icon: 'Instagram' },
  { source: 'TWITTER', name: 'Twitter / X', description: 'Turn X DMs into leads — sender profile + message captured, handle kept.', kind: 'webhook', icon: 'Twitter' },
  { source: 'LINKEDIN', name: 'LinkedIn', description: 'Push LinkedIn DMs and connection enquiries in as tracked leads.', kind: 'webhook', icon: 'Linkedin' },
  { source: 'TELEGRAM', name: 'Telegram', description: 'Forward Telegram bot conversations to your sales pipeline.', kind: 'webhook', icon: 'Send' },
  { source: 'HIKE', name: 'Hike', description: 'Capture Hike chats and enquiries as CRM leads.', kind: 'webhook', icon: 'MessageCircle' },
  { source: 'SNAPCHAT', name: 'Snapchat', description: 'Bring Snapchat business chats into your follow-up flow.', kind: 'webhook', icon: 'Ghost' },
  { source: 'GOOGLE_ADS', name: 'Google Ads', description: 'Pull enquiries generated by your Google Ads campaigns.', kind: 'webhook', icon: 'Search' },
  { source: 'INDIAMART', name: 'IndiaMART', description: 'Receive buyer enquiries from your IndiaMART listings.', kind: 'webhook', icon: 'Store' },
  { source: 'JUSTDIAL', name: 'JustDial', description: 'Bring JustDial business enquiries into your pipeline.', kind: 'webhook', icon: 'PhoneCall' },
  { source: 'TRADEINDIA', name: 'TradeIndia', description: 'Capture TradeIndia seller enquiries as leads.', kind: 'webhook', icon: 'Briefcase' },
  { source: 'SHOPIFY', name: 'Shopify', description: 'Create a lead for every new order or abandoned cart.', kind: 'webhook', icon: 'ShoppingBag' },
  { source: 'ZAPIER', name: 'Zapier', description: 'Connect 5,000+ apps to push leads into PRIMELEAD.', kind: 'webhook', icon: 'Zap' },
  { source: 'API', name: 'REST API', description: 'Push leads programmatically from your own system.', kind: 'api', icon: 'Code2' },
] as const;

router.get(
  '/',
  asyncHandler(async (req, res) => {
    const user = (req as AuthedRequest).user;
    const rows = await prisma.integration.findMany({ where: { orgId: user.orgId }, orderBy: { source: 'asc' } });
    const connections = rows.map((r) => ({
      id: r.id,
      source: r.source,
      name: r.name,
      enabled: r.enabled,
      status: r.status,
      webhookUrl: r.webhookUrl,
      hasWebhookSecret: Boolean(r.webhookSecret),
      lastSyncAt: r.lastSyncAt,
      errorCount: r.errorCount,
      lastError: r.lastError,
      config: r.config ? Object.fromEntries(Object.entries(r.config as Record<string, unknown>).filter(([k]) => !/key|secret|token|password/i.test(k))) : {},
      createdAt: r.createdAt,
    }));
    const catalog = INTEGRATION_CATALOG.map((c) => ({
      ...c,
      connected: rows.some((r) => r.source === c.source),
    }));
    return ok(res, { catalog, connections });
  })
);

/** Generate (or regenerate) a webhook secret + URL for a source. */
router.post(
  '/:source/connect',
  requirePermission('integrations.manage'),
  asyncHandler(async (req, res) => {
    const user = (req as AuthedRequest).user;
    assertManagerOrAbove(user);
    const source = String(req.params.source).toUpperCase();
    const entry = INTEGRATION_CATALOG.find((c) => c.source === source);
    if (!entry) throw badRequest('Unknown integration source.');

    const secret = crypto.randomBytes(24).toString('hex');
    const webhookUrl = `${config.appUrl}/api/webhooks/${source.toLowerCase()}`;
    const existing = await prisma.integration.findFirst({ where: { orgId: user.orgId, source } });
    const integration = existing
      ? await prisma.integration.update({
          where: { id: existing.id },
          data: { webhookSecret: secret, webhookUrl, name: entry.name, enabled: true, status: 'CONNECTED' },
        })
      : await prisma.integration.create({
          data: { orgId: user.orgId, source, name: entry.name, webhookSecret: secret, webhookUrl, enabled: true, status: 'CONNECTED' },
        });

    await audit({
      orgId: user.orgId,
      userId: user.id,
      action: existing ? 'INTEGRATION_SECRET_REFRESHED' : 'INTEGRATION_CONNECTED',
      entity: 'Integration',
      entityId: integration.id,
      metadata: { source },
      req,
    });
    return ok(res, {
      integration: {
        id: integration.id,
        source,
        name: entry.name,
        webhookUrl,
        webhookSecret: secret, // shown exactly once, right here
      },
    });
  })
);

router.patch(
  '/:source',
  requirePermission('integrations.manage'),
  asyncHandler(async (req, res) => {
    const user = (req as AuthedRequest).user;
    assertManagerOrAbove(user);
    const source = String(req.params.source).toUpperCase();
    const input = validate(integrationUpdateSchema, req.body);
    const existing = await prisma.integration.findFirst({ where: { orgId: user.orgId, source } });
    if (!existing) throw badRequest('Connect this integration first.');

    const updated = await prisma.integration.update({
      where: { id: existing.id },
      data: {
        name: input.name ?? undefined,
        enabled: input.enabled ?? undefined,
        status: input.status ?? undefined,
        config: input.config ? (input.config as any) : undefined,
        ...(input.enabled && input.enabled !== existing.enabled ? { lastSyncAt: new Date() } : {}),
      },
    });
    await audit({ orgId: user.orgId, userId: user.id, action: 'INTEGRATION_UPDATED', entity: 'Integration', entityId: existing.id, metadata: { source }, req });
    return ok(res, { updated: true, status: updated.status, enabled: updated.enabled });
  })
);

router.delete(
  '/:source',
  requirePermission('integrations.manage'),
  asyncHandler(async (req, res) => {
    const user = (req as AuthedRequest).user;
    assertManagerOrAbove(user);
    const source = String(req.params.source).toUpperCase();
    const existing = await prisma.integration.findFirst({ where: { orgId: user.orgId, source } });
    if (!existing) throw badRequest('Not connected.');
    await prisma.integration.delete({ where: { id: existing.id } });
    await audit({ orgId: user.orgId, userId: user.id, action: 'INTEGRATION_DISCONNECTED', entity: 'Integration', entityId: existing.id, metadata: { source }, req });
    return ok(res, { deleted: true });
  })
);

/** Recent ingestion activity for a source — the connection's audit trail. */
router.get(
  '/:source/logs',
  requirePermission('integrations.manage'),
  asyncHandler(async (req, res) => {
    const user = (req as AuthedRequest).user;
    const source = String(req.params.source).toUpperCase();
    const existing = await prisma.integration.findFirst({ where: { orgId: user.orgId, source } });
    if (!existing) throw badRequest('Connect this integration first.');
    const status = String(req.query.status || '').toUpperCase();
    const logs = await prisma.integrationLog.findMany({
      where: { orgId: user.orgId, source, ...(status ? { status } : {}) },
      orderBy: { createdAt: 'desc' },
      take: 50,
      include: { integration: { select: { id: true, source: true, status: true, lastSyncAt: true, errorCount: true, lastError: true } } },
    });
    const health = logs[0]?.integration || null;
    return ok(res, {
      logs: logs.map((l) => ({
        id: l.id,
        status: l.status,
        message: l.message,
        error: l.error,
        leadId: l.leadId,
        externalId: l.externalId,
        createdAt: l.createdAt,
      })),
      health: health
        ? { status: health.status, lastSyncAt: health.lastSyncAt, errorCount: health.errorCount, lastError: health.lastError }
        : null,
      counts: {
        success: await prisma.integrationLog.count({ where: { orgId: user.orgId, source, status: 'SUCCESS' } }),
        duplicate: await prisma.integrationLog.count({ where: { orgId: user.orgId, source, status: 'DUPLICATE' } }),
        invalid: await prisma.integrationLog.count({ where: { orgId: user.orgId, source, status: 'INVALID' } }),
        failed: await prisma.integrationLog.count({ where: { orgId: user.orgId, source, status: 'FAILED' } }),
      },
    });
  })
);

export default router;
